baseURL = 'https://tensornetworkwakate.github.io/'
languageCode = 'ja-jp'
hasCJKLanguage = true
title = 'テンソルネットワーク若手の会'
theme = 'PaperMod'
buildDrafts = false
env = 'production'

[params]
defaultTheme = "auto"

[params.label]
text = "テンソルネットワーク若手の会"
icon = "image/icon.png"
iconHeight = 35

[params.profileMode]
enabled = true
title = "テンソルネットワーク若手の会"
subtitle = """
テンソルネットワークに興味を持っている方々の交流や

テンソルネットワークに関する情報の共有を目的としたコミュニティです.

特に, これまで交流が少なかった異分野間の交流を促進することを目指しています.

テンソルネットワークに興味をお持ちの方はどなたでもご参加ください.

"""
imageUrl = "image/icon.png"
imageWidth = 250
imageHeight = 250
imageTitle = "icon"

[[params.socialIcons]]
name = "github"
url = "https://github.com/TensorNetworkWakate/tensornetworkwakate.github.io"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/jgsUUrVSZg"

[[params.profileMode.buttons]]
name = "Discordサーバーに参加する"
url = "https://discord.gg/jgsUUrVSZg"

